# **Desafío: hazlo tú mismo**

Aprendimos a manipular elementos textuales con el comando ```str```. Luego, usamos expresiones regulares para limpiar elementos no deseados en el texto y, finalmente, transformamos el texto tratado en una lista, construyendo un token.

Durante las clases transformamos dos columnas ```descripcion_local``` y ```comodidades``` buscando la tokenización. Pero aún falta la columna ```descripcion_vecindad```, que también merece la pena transformar.

Por lo tanto, en esta actividad te propongo realizar el proceso de tokenización para la columna ```descripcion_vecindad``` presente en el conjunto de datos ```datos_hosting.json```.

---

In [5]:
import pandas as pd
import json
import numpy as np

In [6]:
url = "datos_hosting.json"

hosting_json = json.load(open(url, "r"))

In [7]:
hosting = pd.json_normalize(hosting_json["info_inmuebles"])
hosting.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baÃ±os,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,[This clean and comfortable one bedroom sits r...,[Lower Queen Anne is near the Seattle Center (...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Futon, Futon, Pull-out Sofa, Real B...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...","[$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...","[$110.00, $45.00, $55.00, $52.00, $85.00, $50...."
1,10.0,--,10,[Welcome to the heart of the 'Ballard Brewery ...,"[--, Capital Hill is the heart of Seattle, bor...","[2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]","[3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]","[5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$500.00, $300.00, $0, $300.00, $300.00, $360....","[$125.00, $100.00, $85.00, $110.00, $110.00, $...","[$350.00, $300.00, $425.00, $300.00, $285.00, ..."
2,10.0,--,11,[New modern house built in 2013. Spectacular ...,[Upper Queen Anne is a charming neighborhood f...,[4],[5],[7],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00]",[$300.00],[$975.00]
3,10.0,--,12,[Our NW style home is 3200+ sq ft with 3 level...,[The Views from our top floor! Wallingford ha...,"[3, 3, 3, 3, 3, 3, 3, 3]","[6, 6, 5, 5, 5, 5, 4, 4]","[6, 6, 7, 8, 7, 7, 6, 6]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$500.00, $500.00, $500.00, $500.00, $500.00, ...","[$225.00, $300.00, $250.00, $250.00, $250.00, ...","[$490.00, $550.00, $350.00, $350.00, $350.00, ..."
4,10.0,--,14,"[Perfect for groups. 2 bedrooms, full bathroom...",[Safeway grocery store within walking distance...,"[2, 3]","[2, 6]","[3, 9]","[Real Bed, Real Bed]","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$300.00, $2,000.00]","[$40.00, $150.00]","[$200.00, $545.00]"

In [8]:
columnas_hosting = hosting.columns.tolist()
hosting_explode = hosting.explode(columnas_hosting[3:]).reset_index(drop=True)
hosting_explode['descripcion_local'] = hosting_explode['descripcion_local'].str.lower()
hosting_explode['descripcion_local'] = hosting_explode['descripcion_local'].str.replace(r'[^a-zA-Z0-9\-\']',' ',regex=True)
hosting_explode['descripcion_local'] = hosting_explode['descripcion_local'].str.replace(r'(?<!\w)-(?!\w)',' ',regex=True)
hosting_explode['comodidades'] = hosting_explode['comodidades'].str.replace(r'\{|}|\"','', regex=True)
hosting_explode['descripcion_vecindad'] = hosting_explode['descripcion_vecindad'].str.lower().replace(r'[^a-zA-Z0-9\-\']'," ")
hosting_explode['descripcion_vecindad'] = hosting_explode['descripcion_vecindad'].str.split()
hosting_explode.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baÃ±os,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,this clean and comfortable one bedroom sits ri...,"[lower, queen, anne, is, near, the, seattle, c...",1,1,1,Real Bed,"Internet,Wireless Internet,Kitchen,Free Parkin...",$0,$0,$110.00
1,10.0,--,1,our century old upper queen anne house is loca...,"[upper, queen, anne, is, a, really, pleasant,,...",1,1,1,Futon,"TV,Internet,Wireless Internet,Kitchen,Free Par...",$0,$0,$45.00
2,10.0,--,1,cozy room in two-bedroom apartment along the l...,"[the, convenience, of, being, in, seattle, but...",1,1,1,Futon,"TV,Internet,Wireless Internet,Kitchen,Free Par...",$0,$0,$55.00
3,10.0,--,1,very lovely and cozy room for one convenientl...,"[ballard, is, lovely,, vibrant, and, one, of, ...",1,1,1,Pull-out Sofa,"Internet,Wireless Internet,Kitchen,Free Parkin...",$0,$20.00,$52.00
4,10.0,--,1,the studio at mibbett hollow' is in a beautif...,[--],1,1,1,Real Bed,"Wireless Internet,Kitchen,Free Parking on Prem...",$0,$15.00,$85.00